//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIM.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultSave {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultSave() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIM.Properties.DefaultSave", typeof(DefaultSave).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;playerUId&quot;:&quot;NONE&quot;,&quot;selectedCamperIndex&quot;:3,&quot;selectedSlasherIndex&quot;:268435456,&quot;firstTimePlaying&quot;:false,&quot;currentSeasonTicks&quot;:0,&quot;disconnectPenaltyTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;lastMatchEndTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;lastMatchStartTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;lastKillerMatchEndTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;lastSurvivorMatchEndTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;ongoingGameTime&quot;:&quot;0001-01-01T00:00:00.000Z&quot;,&quot;cumulativeSessions&quot;:1,&quot;cumulativePlaytime&quot;:&quot;0&quot;,&quot;characterData&quot;:[{&quot;key&quot;:268435458,&quot;data&quot;:{&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string OFFLINE_SAVEFILE {
            get {
                return ResourceManager.GetString("OFFLINE_SAVEFILE", resourceCulture);
            }
        }
    }
}
